# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set environment variables
      env:
        DEMO_API_TOKEN: ${{ secrets.DEMO_API_TOKEN }}
        DEMO_APIACCOUNT: ${{ vars.DEMO_APIACCOUNT }}
        DEMO_APIURL: ${{ vars.DEMO_APIURL }}
      run: |
        echo "Environment variables set:"
        echo "DEMO_API_TOKEN=${{ secrets.DEMO_API_TOKEN }}" # Avoid printing sensitive secrets in real workflows
        echo "DEMO_APIACCOUNT=${{ vars.DEMO_APIACCOUNT }}"
        echo "DEMO_APIURL=${{ vars.DEMO_APIURL }}"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     python -m pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      env:
        APITOKEN: ${{ secrets.DEMO_API_TOKEN }}
        APIACCOUNT: ${{ vars.DEMO_APIACCOUNT }}
        APIURL: ${{ vars.DEMO_APIURL }}
      run: |
        pytest ./tests/
        pytest ./src/ --doctest-modules -v

