name: Create Release

on:
  push:
    branches:
      - main
      - Dev

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion to work correctly

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0

      - name: Extract Release Notes from Changelog
        id: extract-changelog
        uses: release-flow/keep-a-changelog-action@v3.0.0
        with:
          command: query
          version: ${{ steps.gitversion.outputs.semVer }}

      - name: Update CHANGELOG.md
        if: github.ref == 'refs/heads/main'  # Only update for stable releases
        uses: release-flow/keep-a-changelog-action@v3.0.0
        with:
          command: bump
          version: ${{ steps.gitversion.outputs.semVer }}

      - name: Commit Updated CHANGELOG.md
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CHANGELOG for release ${{ steps.gitversion.outputs.semVer }}"
          file_pattern: "ChangeLog.md"

      - name: Create Git Tag
        run: |
          git tag ${{ steps.gitversion.outputs.semVer }}
          git push origin ${{ steps.gitversion.outputs.semVer }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          name: Release ${{ steps.gitversion.outputs.semVer }}
          body: "${{ steps.extract-changelog.outputs.changes }}"
          draft: false
          prerelease: ${{ github.ref == 'refs/heads/Dev' }}
